# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: airbox

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/airbox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    wrap_in_directory: true
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  disable: true