on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  create-release:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo "ABCTL_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
           go-version: 'stable'
      - name: Make Release
        run: make clean release
      - name: Check version
        run: ./build/release/abctl-$ABCTL_VERSION-linux-amd64/abctl version
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "build/release/*.tar.gz,build/release/*.zip"
      - uses: actions/checkout@v4
        with:
          repository: airbytehq/homebrew-tap
          ssh-key: ${{ secrets.ABCTL_HOMEBREW_KEY }}
      - name: Replace version
        run: |
          sed -i 's/ABCTL_VERSION = ".*"/ABCTL_VERSION = "'$ABCTL_VERSION'"/' Formula/abctl.rb
      - name: Show diff
        run: git diff
      - name: Commit changes
        run: |
          git config user.email ${{ secrets.PRODENG_BOT_EMAIL }}
          git config user.name "airbyte-prodeng"
          git commit -a -m "chore: update abctl to $ABCTL_VERSION"
      - name: Push change
        run: git push
        
